spring:

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./industria
#    url: jdbc:h2:mem:industria
    username: admin
    password:
    driverClassName: org.h2.Driver
    hikari:
      maximum-pool-size: 1
      pool-name: application-teste

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      jdbc:
        lob:
          non_contextual_creation: true

  h2:
    console:
      enabled: true
      path: /h2-database
